// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlx4ChCK--t58iap5-rcQVitws4yxFyGI',
    appId: '1:718629896603:web:8da7448047b10d903da13e',
    messagingSenderId: '718629896603',
    projectId: 'mylez-weatherly-app',
    authDomain: 'mylez-weatherly-app.firebaseapp.com',
    storageBucket: 'mylez-weatherly-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVbr23mM5Z3xFL6X4a-2KXDSPmDkNg4Dw',
    appId: '1:718629896603:android:d5a0a0a1e7d1d5e43da13e',
    messagingSenderId: '718629896603',
    projectId: 'mylez-weatherly-app',
    storageBucket: 'mylez-weatherly-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrFio_Lkpep6yb7fCyriiUobRdquk7MEg',
    appId: '1:718629896603:ios:9ca87f17936684073da13e',
    messagingSenderId: '718629896603',
    projectId: 'mylez-weatherly-app',
    storageBucket: 'mylez-weatherly-app.appspot.com',
    iosClientId: '718629896603-68inrkgf33p3q54tqe0u6nmmiopdcm7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrFio_Lkpep6yb7fCyriiUobRdquk7MEg',
    appId: '1:718629896603:ios:9ca87f17936684073da13e',
    messagingSenderId: '718629896603',
    projectId: 'mylez-weatherly-app',
    storageBucket: 'mylez-weatherly-app.appspot.com',
    iosClientId: '718629896603-68inrkgf33p3q54tqe0u6nmmiopdcm7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherly',
  );
}
